# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c02d5f678534fa60937a4ba35c86270e"
name = "polar-skate-co-usa-riders"
handle = "polar-skate-co-usa-riders"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
