name: Deploy Extensions

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Enter the 3 shopify api codes for the three different extensions.
        target: ['3882cd7de0823cc5697d21968ba3e2e1', 'fe41bd81dd1aa26c2e000a18ce324e8a', 'c02d5f678534fa60937a4ba35c86270e']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install npm dependencies
        run: npm install --ci
      - name: Build
        run: npm run build
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest
      - name: Deploy
        env:
          # Token from the partner dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          SHOPIFY_API_KEY: ${{ matrix.target }}
        run: npm run deploy -f --source-control-url=$COMMIT_URL